# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20160613_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='answer_liked', to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='question_liked', to='account.Profile'),
        ),
    ]
